### ISSUE TITLE
Duplicate services on servicegroup widget

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-servicegroup-monitoring#2]
---

Author Name: **Wagner Sartori Junior** (Wagner Sartori Junior)
Original Redmine Issue: 4473, https://forge.centreon.com/issues/4473
Original Date: 2013-05-16

---

Hi,

Servicegroup widgets are showing duplicate services on detailed mode with name search = some servicegroup. See screenshots.

I'm using centreon 2.4.2 with Servicegroup Monitoring widget version 1.1.0.

Thanks,

Wagner Sartori Junior

**Comment by joschi99** [comment]
Upgraded the service group widget to version 1.2.1. The problem is still there and not resolved. Can you reopen the bug?

Example:
Servicegroup ONDATEL
* 1 Host
* 4 Services OK
* 1 Service Critical
![servicegroup_normal](https://cloud.githubusercontent.com/assets/6400595/10941573/5ee22abe-830c-11e5-89e9-427e0119cc7b.png)

Servicegroup Widget
* 4 Hosts
* 16 Services OK
* 4 Services Critical
![servicegroup](https://cloud.githubusercontent.com/assets/6400595/10941585/6c7cba22-830c-11e5-9f7d-bbcc256c68a3.png)

Screenshot widget versions:
![widget-version](https://cloud.githubusercontent.com/assets/6400595/10941594/7472726c-830c-11e5-9d69-a4402d61cb0b.png)
